sudo: false

language: java
jdk:
  - oraclejdk8
env:
  global:
    - secure: "Lcd0U7ANJto94xmYF2Y4mxCPcl3jaqVrnTP8jXHqyhkonIX8cvbgCkjjZ/mrDz5TopVBSuVo7HSG95j7K4zzhHEidBBXjoyXcOnNgOZ3bq9deyKgf3O5XWv5mdOv2k6h4DY6ucNtvAxfr+dzCZfnWTM54l6ivGs5AhaD93cnc3zI85MAepdmz8PMciK45eRsieLq4ubzQOd0Bmd5wi2C9aHS/56IaBzVOwtL16Du8SRLzEHvjzyiM/cFFCaEjgcS6/5YPOpm+qjLVzHY4q2F4YwcyMypWkpE6NmkklOYeTS2YHMDpL+Iax64mNSDIQ4mcPaT4j2X+JAHor7SQNJO70EoQpY79TskitpnYJ8yhzBWvG13+djTJB7kMLjlVTnzTwCM3BsC6VytcRboE3kTIYv0ZfyGUo0TLgCAiHxHRkd/tFyi2BJ+2yYbX78h4PDZsvJLeSKKqH/Fo6eR38b7ONcGsbXvC8+R0G1SqpLzxZitjQ1+HntEdvhPFmPRFwz7+YJEgKJ2AS2kG5/IyUkIxW2UOU+gJ8rVy8ZecJM8GCmH3/uceijvxN36AQTub7niHwxQGP7X+d5nsLWhatcdfLSXlxrv2vuw8aQFDsqtPTCYQJm9RvUgp67QxeayfVzqebWGucS14L2KT700bOzT+M60vHXdbmFvd4hNtNCJAw0="
cache:
  directories:
    - $HOME/.m2
  
script: 
  - "mvn cobertura:cobertura"
  - "mvn javadoc:javadoc"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash Deploy_JavaDoc.sh

notification:
  email:
    on_success: never
    on_failure: always
